---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret.value: AgBMG5bE1PnU6diB7C8t17L8Yb2Vrd5M6UmmfV0U6L/wuQMaIEPR18fir6c3BK+/KMmtYZngEvaYyQyfCOlqwOnPUx7dyZqJNX39mjEAlCwWAYxoyxFeW3fRjp5HmTnLgCww0OqvvOx+9s8MzQ+JBXRqxrWGCSKK6VJesC1aA0Kr4z6KfkDvsGL4oNDyMWbcJuu0kaIIq1XMNjuT9nAe7So/oYAot0X0kAd/CSXY63LtAOK6JRRq6YddYDODQtAJ4h5/0Cc/3+Ko78YfxHA0R9kstNt6KjWJ+3I3D40l5vpXLn7VdYYZWvm8YvD8UijSqhkp30vGNlA/amBgMKDPYf1mnVHFZaFhrzjUOyZzMWERuiBZZnfxAin+A0KPjbfuka89JbKhDmklc42QUO9wD7iN8JpisI8LvkW2NMtAWZ3behT4SpCkG+HFt0Ka+VYeczoghzkqyANrcp15xZRg6xxSwElbnKKyhtGGlq7lYr6Cp/hr5sMeEtz2vGezVFHAqm2sdEqvJd8l2r0U/oo+PX0cf7mWg6W3/2Cl3S6sVZXWTGkBfF+9XsOiVzYcRxvYezfeIhXkfL+A4LHxZWVAP+xMHdO9KT64SYTkyXVCfEX1YesoIP4Cm6MI7MVx1BnMKiwT9LPsKrV9bIzRknFODBO3PcZAz/XyjcYrxz+cv8/KxNMeR1iOazL3EYpE7INYOuc5j0YU435kFlOyOA==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
