apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "secrets-app-chart.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "secrets-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "secrets-app-chart.backendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{ .Values.deployment.name }}container"
          image: "{{ .Values.deployment.image.app }}:{{ .Values.deployment.image.version }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          env:
            {{- range .Values.deployment.env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- else }}
              value: "{{ .value }}"
              {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP